# Pima Data cleaning

In [1]:
# Import Modules Here
import pandas as pd

## Part 1: Read the Data into Jupyter

In [2]:
# Read the data into a dataframe named pima_df.
# YOUR CODE HERE
pima_df=pd.read_csv('diabetes_uncleaned_data.csv')

## Part 2: Missing Data

In [3]:
#Question 1:  Find Columns with missing data
# YOUR CODE HERE
missing_columns = pima_df.columns[pima_df.isna().any()]
print(missing_columns)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'BMI', 'Age'], dtype='object')

In [4]:
# Question 2:  Write code to remove rows with missing data and save the new dataframe as pima_missing_fixed_df
# YOUR CODE HERE
pima_missing_fixed_df = pima_df.dropna()

pima_missing_fixed_df.to_csv('pima_missing_fixed.csv')

In [5]:
# Question 3:  Print out the number of rows in the dataframe.
# YOUR CODE HERE

print(pima_missing_fixed_df.shape[0])

840

### Question 4:  Discuss why this could be a problem.  What other methods could you use in this situation? 

By removing the whole row when dealing with missing data, can lead to a loss of data during analysis. A way to deal with this situation would be to to just remove the missing value instead of a whole row which could potentially skew the data immensely.

## Part 3: Duplicated Data

In [6]:
# Question 1: find the rows of duplicated data in the 
# pima_missing_fixed_df and print them.  

duplicated_rows = pima_missing_fixed_df[pima_missing_fixed_df.duplicated()]
print(duplicated_rows)

      Pregnancies  Glucose BloodPressure  SkinThickness  Insulin   BMI  \
925           6.0     39.0            46              2      287  40.4
926          10.0     67.0            39             12      168  53.4
999           6.0    110.0            26             27      590  20.8
1003          6.0    151.0            60             26      362  43.4

      DiabetesPedigreeFunction   Age Outcome
925                      2.394  60.0    TRUE
926                      0.162  71.0   FALSE
999                      1.185  95.0   FALSE
1003                     2.027  23.0   FALSE

In [7]:
# Question 2: Write code to remove rows with missing data 
# and save the new dataframe as pima_dedupped_df

pima_dedupped_df = pima_missing_fixed_df.drop_duplicates()

pima_dedupped_df.to_csv('pima_dedupped.csv')

In [8]:
# Question 3:  Print out the number of rows in the dataframe.
print(pima_dedupped_df.shape[0])

836

## Part 4: Mis-typed Columns/Broken Data

In [9]:
# Question 1: find the columns where most of the data seems to be one type of data, and there seems to be a data error. In the markdown, after exploring in code, add a markdown cell discussing which columns have the data error. 
pima_dedupped_df.info()
display(pima_dedupped_df['BloodPressure'].value_counts())
display(pima_dedupped_df['BMI'].value_counts())
display(pima_dedupped_df['Outcome'].value_counts())

<class 'pandas.core.frame.DataFrame'>
Index: 836 entries, 0 to 1002
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               836 non-null    float64
 1   Glucose                   836 non-null    float64
 2   BloodPressure             836 non-null    object
 3   SkinThickness             836 non-null    int64
 4   Insulin                   836 non-null    int64
 5   BMI                       836 non-null    object
 6   DiabetesPedigreeFunction  836 non-null    float64
 7   Age                       836 non-null    float64
 8   Outcome                   836 non-null    object
dtypes: float64(4), int64(2), object(3)
memory usage: 65.3+ KB

BloodPressure
26       15
82       15
27       15
96       15
81       13
         ..
107       4
13        3
10000     2
Error     2
19        1
Name: count, Length: 113, dtype: int64

BMI
7.0     6
17.4    6
59.6    6
15.1    6
34.4    5
       ..
33.7    1
38.2    1
1.7     1
3.6     1
4.8     1
Name: count, Length: 451, dtype: int64

Outcome
FALSE    441
TRUE     394
ERROR      1
Name: count, dtype: int64

In [15]:
# Question 2: Remove the rows with data errors
pima_remove_errordf=pima_dedupped_df[(pima_dedupped_df['BloodPressure']!='Error')&(pima_dedupped_df['BMI']!='Error')&(pima_dedupped_df['Outcome']!='ERROR')]

pima_remove_errordf['Insulin'].count()

832

In [16]:
# Question 3: After the data is fixed in your columns change the columns to the correct type and save this as the pima_fixed_columns_df.
pima_fixeddf=pima_remove_errordf.copy()
pima_fixeddf['BloodPressure']=pima_fixeddf['BloodPressure'].astype('int')
pima_fixeddf['BMI']=pima_fixeddf['BMI'].astype('float')

def convert_bool(x):
    print(x)
    if x=="FALSE":
        return False
    elif x=="TRUE":
        return True
    
pima_fixeddf['Outcome']=pima_fixeddf['Outcome'].apply(convert_bool)

FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
FALSE
TRUE
TRUE
FALSE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
TRUE
FALSE
TRUE
TRUE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
TRUE
TRUE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
FALSE
TRUE
FALSE
FALSE
FALSE
TRUE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
TRUE
FALSE
FALSE
FALSE
TRUE
FALSE
TRUE
FALSE
TRUE
TRUE
FALSE
FALSE
TRUE
FALSE
TRUE

In [17]:
# Question 4: Run pima_fixed_columns_df.info() to confirm the columns have changed.
pima_fixeddf.info()
display(pima_fixeddf)

<class 'pandas.core.frame.DataFrame'>
Index: 832 entries, 0 to 1001
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               832 non-null    float64
 1   Glucose                   832 non-null    float64
 2   BloodPressure             832 non-null    int64
 3   SkinThickness             832 non-null    int64
 4   Insulin                   832 non-null    int64
 5   BMI                       832 non-null    float64
 6   DiabetesPedigreeFunction  832 non-null    float64
 7   Age                       832 non-null    float64
 8   Outcome                   832 non-null    bool
dtypes: bool(1), float64(5), int64(3)
memory usage: 59.3 KB

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3.0,167.0,39,28,545,53.0,2.447,125.0,False
1,13.0,151.0,107,38,10000,9.2,0.507,148.0,False
2,8.0,59.0,109,18,739,59.1,1.769,91.0,True
4,10.0,165.0,48,37,737,39.4,0.729,73.0,False
5,-100.0,142.0,88,39,82,42.7,1.369,148.0,True
...,...,...,...,...,...,...,...,...,...
995,5.0,62.0,10000,13,412,48.7,0.267,101.0,False
996,6.0,117.0,91,28,212,1.0,1.969,137.0,False
997,13.0,163.0,10,37,457,8.0,2.400,125.0,True
998,6.0,110.0,26,27,590,20.8,1.185,95.0,False
1001,4.0,80.0,24,6,268,48.9,0.989,81.0,True

## Part 5: Outlier Detection and Removal

In [36]:
# Question 1: Print out the Outliers in each column in the pima_fixed_columns_df dataframe, use the IQR method of outlier detection.
def is_iqr_outlier(column):
    q1 = column.quantile(0.25)
    q3 = column.quantile(0.75)
    IQR = q3 - q1
    lower = q1 - (1.5 * IQR)
    higher = q3 + (1.5 * IQR)
    return ~column.between(lower, higher)

display(pima_fixeddf[is_iqr_outlier(pima_fixeddf['Pregnancies'])])

display(pima_fixeddf[is_iqr_outlier(pima_fixeddf['Glucose'])])

display(pima_fixeddf[is_iqr_outlier(pima_fixeddf['BloodPressure'])])

display(pima_fixeddf[is_iqr_outlier(pima_fixeddf['SkinThickness'])])

display(pima_fixeddf[is_iqr_outlier(pima_fixeddf['Insulin'])])

display(pima_fixeddf[is_iqr_outlier(pima_fixeddf['BMI'])])

display(pima_fixeddf[is_iqr_outlier(pima_fixeddf['DiabetesPedigreeFunction'])])

display(pima_fixeddf[is_iqr_outlier(pima_fixeddf['Age'])])

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
5,-100.0,142.0,88,39,82,42.7,1.369,148.0,True

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
649,3.0,155.0,10000,35,748,32.6,0.098,85.0,True
995,5.0,62.0,10000,13,412,48.7,0.267,101.0,False

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,13.0,151.0,107,38,10000,9.2,0.507,148.0,False

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [60]:
# Question 2: Use loc to remove outliers in each of the columns that have outliers, save this as pima_outlier_removed_df.

pima_outlier_removed_df = pima_fixeddf.copy()

pima_outlier_removed_df=pima_fixeddf[is_iqr_outlier(pima_fixeddf['Pregnancies'])==False]

print(pima_outlier_removed_df.count())

pima_outlier_removed_df=pima_fixeddf[is_iqr_outlier(pima_fixeddf['BloodPressure'])==False]

print(pima_outlier_removed_df.count())

outlier3df=pima_fixeddf[is_iqr_outlier(pima_fixeddf['Insulin'])==False]

print(outlier3df.count())



pima_outlier_removed_df.to_csv('pima_outlier_removed.csv')

Pregnancies                 831
Glucose                     831
BloodPressure               831
SkinThickness               831
Insulin                     831
BMI                         831
DiabetesPedigreeFunction    831
Age                         831
Outcome                     831
dtype: int64
Pregnancies                 830
Glucose                     830
BloodPressure               830
SkinThickness               830
Insulin                     830
BMI                         830
DiabetesPedigreeFunction    830
Age                         830
Outcome                     830
dtype: int64
Pregnancies                 831
Glucose                     831
BloodPressure               831
SkinThickness               831
Insulin                     831
BMI                         831
DiabetesPedigreeFunction    831
Age                         831
Outcome                     831
dtype: int64

In [61]:
# Question 3:  Print out the row count in the pima_outlier_removed_df and confirm this number is correct.
print(pima_outlier_removed_df.shape[0])

830